"""initial schema

Revision ID: 368b13ae34f1
Revises: 
Create Date: 2026-04-01 04:22:00.617645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368b13ae34f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arenas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('buy_in', sa.Integer(), nullable=False),
    sa.Column('small_blind', sa.Integer(), nullable=False),
    sa.Column('big_blind', sa.Integer(), nullable=False),
    sa.Column('reward_multiplier', sa.Float(), nullable=False),
    sa.Column('is_practice', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('bot_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('preset_origin', sa.String(length=20), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('hands_played', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'version_number', name='uq_bot_version')
    )
    op.create_index(op.f('ix_bot_versions_bot_id'), 'bot_versions', ['bot_id'], unique=False)
    op.create_table('bots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('total_losses', sa.Integer(), nullable=False),
    sa.Column('total_hands', sa.Integer(), nullable=False),
    sa.Column('active_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['bot_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    op.create_table('season_rankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('winrate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'entity_type', 'entity_id', name='uq_season_entity')
    )
    op.create_index(op.f('ix_season_rankings_entity_id'), 'season_rankings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_season_rankings_season'), 'season_rankings', ['season'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('bot_version_id', sa.String(length=36), nullable=False),
    sa.Column('arena_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('opponent_session_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('buy_in', sa.Integer(), nullable=False),
    sa.Column('initial_stack', sa.Integer(), nullable=False),
    sa.Column('final_stack', sa.Integer(), nullable=True),
    sa.Column('hands_played', sa.Integer(), nullable=False),
    sa.Column('hands_won', sa.Integer(), nullable=False),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('elo_before', sa.Integer(), nullable=True),
    sa.Column('elo_after', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arena_id'], ['arenas.id'], ),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['bot_version_id'], ['bot_versions.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_arena_id'), 'sessions', ['arena_id'], unique=False)
    op.create_index(op.f('ix_sessions_bot_id'), 'sessions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('arena_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seat_1_session_id', sa.String(length=36), nullable=True),
    sa.Column('seat_2_session_id', sa.String(length=36), nullable=True),
    sa.Column('hands_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arena_id'], ['arenas.id'], ),
    sa.ForeignKeyConstraint(['seat_1_session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['seat_2_session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_arena_id'), 'tables', ['arena_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('locked_balance', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('registration_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('session_1_id', sa.String(length=36), nullable=False),
    sa.Column('session_2_id', sa.String(length=36), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('winner_session_id', sa.String(length=36), nullable=True),
    sa.Column('pot', sa.Integer(), nullable=False),
    sa.Column('community_cards', sa.String(length=100), nullable=True),
    sa.Column('player_1_hole', sa.String(length=20), nullable=True),
    sa.Column('player_2_hole', sa.String(length=20), nullable=True),
    sa.Column('player_1_stack_after', sa.Integer(), nullable=False),
    sa.Column('player_2_stack_after', sa.Integer(), nullable=False),
    sa.Column('winning_hand_rank', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_1_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['session_2_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hands_table_id'), 'hands', ['table_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('hand_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hand_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=10), nullable=False),
    sa.Column('player_seat', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('pot_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hand_events_hand_id'), 'hand_events', ['hand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hand_events_hand_id'), table_name='hand_events')
    op.drop_table('hand_events')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_hands_table_id'), table_name='hands')
    op.drop_table('hands')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tables_arena_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_bot_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_arena_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_season_rankings_season'), table_name='season_rankings')
    op.drop_index(op.f('ix_season_rankings_entity_id'), table_name='season_rankings')
    op.drop_table('season_rankings')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_bot_versions_bot_id'), table_name='bot_versions')
    op.drop_table('bot_versions')
    op.drop_table('arenas')
    # ### end Alembic commands ###
