"""add_hand_strength_hole_cards_to_events

Revision ID: 74a8b70cf1d3
Revises: 368b13ae34f1
Create Date: 2026-04-01 10:28:44.160406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a8b70cf1d3'
down_revision: Union[str, None] = '368b13ae34f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hand_events', sa.Column('hand_strength', sa.Float(), nullable=True))
    op.add_column('hand_events', sa.Column('hole_cards', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hand_events', 'hole_cards')
    op.drop_column('hand_events', 'hand_strength')
    # ### end Alembic commands ###
